export interface ToolMeta {
  path: string;
  title: string;
  description: string;
  heading: string;
  subheading: string;
}

export const SEO_ALIASES: Record<string, string> = {
  '/visual-editor': '/edit-pdf',
  '/offline-pdf-redaction': '/redact-pdf',
};

/*
 * Priority crawl targets.
 *
 * These are the pages we want the homepage/static shell to surface most
 * clearly while the domain is still earning crawl frequency and authority.
 * Keep this list intentionally small instead of treating every tool as equal.
 */
export const SEO_PRIORITY_PATHS = [
  '/pdf-to-word',
  '/bank-statement-to-excel',
  '/document-data-extractor',
  '/private-pii-secrets-auto-redactor',
  '/sanitize-pdf',
  '/ocr-pdf',
  '/compress-pdf',
  '/compress-pdf-to-100kb',
  '/compress-pdf-to-300kb',
  '/compress-pdf-to-1mb',
  '/compress-pdf-to-2mb',
  '/booklet-pdf',
  '/pdf-to-markdown',
  '/redact-pdf',
] as const;

/*
 * Only publish lastmod when we can support the date with a meaningful
 * page/content SEO change. Do not stamp every deployment as "fresh".
 */
export const SEO_LASTMOD: Record<string, string> = {
  '/': '2026-09-23',
  '/blog': '2026-09-24',
  '/blog/how-to-straighten-crooked-scanned-pdf': '2026-09-24',
  '/blog/deskew-pdf-before-ocr': '2026-09-24',
  '/blog/how-to-print-pdf-as-booklet': '2026-09-24',
  '/blog/booklet-imposition-vs-two-pages-per-sheet': '2026-09-24',
  '/blog/pdf-wont-open-corrupted-or-viewer-problem': '2026-09-24',
  '/blog/what-pdf-repair-can-and-cannot-recover': '2026-09-24',
  '/blog/bates-numbering-for-legal-discovery': '2026-09-24',
  '/blog/bates-numbering-vs-page-numbers': '2026-09-24',
  '/blog/extract-pdf-tables-to-excel': '2026-09-24',
  '/blog/scanned-pdf-tables-to-excel-ocr': '2026-09-24',
  '/blog/pdf-to-markdown-for-rag': '2026-09-24',
  '/blog/scanned-pdf-to-markdown-ocr-first': '2026-09-24',
  '/blog/pdf-to-word-without-losing-formatting': '2026-09-24',
  '/blog/scanned-pdf-to-word-ocr-first': '2026-09-24',
  '/blog/how-to-permanently-redact-pdf': '2026-09-24',
  '/blog/redact-pdf-without-uploading': '2026-09-24',
  '/blog/redact-bank-statement-pdf': '2026-09-24',
  '/blog/bank-statement-pdf-to-csv': '2026-09-24',
  '/blog/scanned-bank-statement-to-excel-ocr': '2026-09-24',
  '/blog/india-pdf-upload-size-limits-2026': '2026-09-24',
  '/blog/pdf-privacy-comparison-2026': '2026-09-23',
  '/pdf-to-word': '2026-09-24',
  '/bank-statement-to-excel': '2026-09-24',
  '/document-data-extractor': '2026-09-24',
  '/pdf-to-csv': '2026-09-24',
  '/private-pii-secrets-auto-redactor': '2026-09-23',
  '/sanitize-pdf': '2026-09-21',
  '/bates-numbering': '2026-09-24',
  '/repair-pdf': '2026-09-24',
  '/booklet-pdf': '2026-09-24',
  '/deskew-pdf': '2026-09-24',
  '/ocr-pdf': '2026-09-21',
  '/compress-pdf': '2026-09-24',
  '/compress-pdf-to-50kb': '2026-09-24',
  '/compress-pdf-to-100kb': '2026-09-24',
  '/compress-pdf-to-200kb': '2026-09-24',
  '/compress-pdf-to-300kb': '2026-09-24',
  '/compress-pdf-to-500kb': '2026-09-24',
  '/compress-pdf-to-1mb': '2026-09-24',
  '/compress-pdf-to-2mb': '2026-09-24',
  '/pdf-to-markdown': '2026-09-24',
  '/extract-pdf-for-llm': '2026-09-24',
  '/redact-pdf': '2026-09-24',
};

export const TOOLS_METADATA: Record<string, ToolMeta> = {
  '/compress-pdf-to-50kb': {
    path: '/compress-pdf-to-50kb', title: 'Compress PDF to 50KB Online — Free & Private | 1into1',
    description: 'Aim for a 50KB PDF target directly in your browser for strict form and application upload limits. Review readability before downloading the locally processed result.',
    heading: 'Compress PDF to 50KB Online', subheading: 'Target 50KB for strict upload portals while keeping the PDF on your device during processing.',
  },
  '/': {
    path: '/',
    title: '1into1 PDF — Free, Private PDF & Image Tools (Zero Uploads)',
    description: 'Compress, merge, split, OCR, and convert PDFs and HEIC images 100% locally in your browser. Local PDF tools with optional cloud AI.',
    heading: 'Free PDF Tools That Never Upload Your Files',
    subheading: 'Local-first processing powered by your browser memory. Use local PDF tools with optional cloud AI.',
  },
  '/compress-pdf': {
    path: '/compress-pdf',
    title: 'Compress PDF Online to Exact Size — Private & Local | 1into1',
    description: 'Compress PDF online to a chosen KB target or reduce file size with standard compression. Your document is processed locally in your browser.',
    heading: 'Compress PDF Online to Exact File Size',
    subheading: 'Reduce PDF size or choose a specific KB target without uploading your document for processing.',
  },
  '/merge-pdf': {
    path: '/merge-pdf',
    title: 'Merge PDF Online & Offline — Combine PDF Files Privately',
    description: 'Merge multiple PDF files into one single document client-side with zero data uploads.',
    heading: 'Merge Multiple PDFs',
    subheading: 'Combine and organize your documents without sending files to remote servers.',
  },
  '/split-pdf': {
    path: '/split-pdf',
    title: 'Split PDF Pages Privately — Zero Server Uploads',
    description: 'Extract pages or split PDF documents into multiple files completely offline.',
    heading: 'Split PDF Documents',
    subheading: 'Separate individual pages or ranges locally on your device.',
  },
  '/annotate-pdf': {
    path: '/annotate-pdf',
    title: 'Annotate PDF Online — Draw, Highlight & Add Text Privately | 1into1',
    description: 'Annotate PDF files directly in your browser. Add text, freehand drawings, highlights, rectangles, circles and arrows without uploading your document.',
    heading: 'Annotate PDF Online',
    subheading: 'Add text, highlights, drawings, shapes and arrows to PDF pages privately in your browser.',
  },

  '/edit-pdf': {
    path: '/edit-pdf',
    title: 'Edit PDF Online — Add Text, Whiteout & Shapes Privately | 1into1',
    description: 'Edit PDF files directly in your browser. Add text, cover existing content, place shapes, move and resize edits without uploading your document.',
    heading: 'Edit PDF Online',
    subheading: 'Add text, whiteout areas and visual edits directly to PDF pages with private browser-based processing.',
  },

  '/scan-to-pdf': {
    path: '/scan-to-pdf',
    title: 'Scan to PDF Online — Private Camera & Photo Scanner | 1into1',
    description: 'Scan documents with your camera or photos and create a PDF directly in your browser. Rotate, reorder, use grayscale or B&W, and process files without uploading them.',
    heading: 'Scan Documents to PDF',
    subheading: 'Turn camera scans and photos into an ordered PDF directly on your device.',
  },
  '/image-converter': {
    path: '/image-converter',
    title: 'Image to PDF & Other Formats — JPG, PNG, WebP & HEIC | 1into1',
    description: 'Convert JPG, PNG, WebP, HEIC and HEIF images to PDF, JPG, PNG or WebP directly in your browser with private local processing.',
    heading: 'Image to PDF & other formats',
    subheading: 'Convert images to PDF, JPG, PNG or WebP without uploading your files.',
  },
  '/pdf-to-image': {
    path: '/pdf-to-image',
    title: 'PDF to Image Converter — JPG, PNG & WebP | 1into1',
    description: 'Convert PDF pages to JPG, PNG or WebP images directly in your browser and download individual pages or a ZIP archive.',
    heading: 'PDF to Image Converter',
    subheading: 'Turn every PDF page into JPG, PNG or WebP images privately on your device.',
  },

  '/image-to-pdf': {
    path: '/image-to-pdf',
    title: 'Convert Images to PDF — JPG, PNG to PDF Locally',
    description: 'Convert JPG, PNG, and WebP images to high-quality PDF files directly in your browser.',
    heading: 'Image to PDF Converter',
    subheading: 'Bundle images into a clean PDF document without cloud processing.',
  },
  '/pdf-to-jpg': {
    path: '/pdf-to-jpg',
    title: 'Convert PDF to JPG Images — High Resolution & Private',
    description: 'Render and extract high-resolution JPG images from any PDF file locally.',
    heading: 'PDF to High-Res JPG',
    subheading: 'Export each PDF page as an image directly in your browser session.',
  },
  '/compress-image': {
    path: '/compress-image',
    title: 'Compress Image Online Privately — JPG, PNG, WebP & HEIC | 1into1',
    description: 'Compress JPG, PNG, WebP, HEIC and other common images to a target file size directly in your browser. Optional EXIF, GPS and camera metadata removal with zero server uploads.',
    heading: 'Compress Images Without Uploading Them',
    subheading: 'Reduce image file size locally, choose a target KB size, and optionally remove EXIF, GPS and camera metadata.',
  },
  '/heic-to-jpg': {
    path: '/heic-to-jpg',
    title: 'HEIC to JPG Converter Online & Private (EXIF Stripped) | 1into1',
    description: 'Convert iPhone HEIC/HEIF photos to JPG locally in your browser. Automatically strip GPS location and private camera EXIF data with zero server uploads.',
    heading: 'Convert HEIC to JPG & Strip EXIF',
    subheading: 'Convert Apple photos to standard JPG and remove sensitive GPS metadata locally.',
  },
  '/remove-pages': {
    path: '/remove-pages',
    title: 'Delete PDF Pages — Clean & Remove Unwanted Pages',
    description: 'Remove unwanted pages from your PDF file without uploading confidential data.',
    heading: 'Remove PDF Pages',
    subheading: 'Select and permanently delete pages from your document in memory.',
  },
  '/watermark-pdf': {
    path: '/watermark-pdf',
    title: 'Add Watermark to PDF — In-Browser PDF Protection',
    description: 'Add custom text watermarks to all PDF pages securely without server uploads.',
    heading: 'Watermark PDF',
    subheading: 'Protect confidential files by adding custom stamps locally.',
  },
  '/page-numbers': {
    path: '/page-numbers',
    title: 'Add Page Numbers to PDF — Flexible Formatting Locally',
    description: 'Number PDF pages with customizable positioning and styles completely offline.',
    heading: 'Insert Page Numbers',
    subheading: 'Add sequential pagination across your PDF without tracking.',
  },
  '/pdf-to-text': {
    path: '/pdf-to-text',
    title: 'Extract Text from PDF — Private In-Browser Text Reader',
    description: 'Extract raw text from PDF files directly inside the browser using WebAssembly.',
    heading: 'Extract PDF Text',
    subheading: 'Copy raw text content from your documents with zero network requests.',
  },
  '/sign-pdf': {
    path: '/sign-pdf',
    title: 'Sign PDF Document Privately — Draw & Place Signatures',
    description: 'Electronically sign contracts and forms directly in your browser without cloud uploads.',
    heading: 'Sign PDF',
    subheading: 'Draw and place your electronic signature securely on any PDF page.',
  },
  '/protect-pdf': {
    path: '/protect-pdf',
    title: 'Password Protect PDF Online — 128-bit Local Encryption | 1into1',
    description: 'Add standard 128-bit password protection to a PDF directly in your browser. Create an encrypted copy without sending the document to a processing server.',
    heading: 'Protect PDF',
    subheading: 'Add standard 128-bit password protection to your PDF directly on your device.',
  },
  '/unlock-pdf': {
    path: '/unlock-pdf',
    title: 'Unlock Protected PDF — Remove PDF Password Locally',
    description: 'Decrypt and remove password restrictions from your PDF files without server logs.',
    heading: 'Unlock PDF',
    subheading: 'Decrypt and save an unrestricted copy entirely on your machine.',
  },
  '/edit-metadata': {
    path: '/edit-metadata',
    title: 'Edit PDF Metadata — Title, Author, Subject & Keywords | 1into1',
    description: 'Inspect and change PDF title, author, subject and keywords locally in your browser. Save an updated copy without uploading the document for processing.',
    heading: 'Edit PDF Metadata Locally',
    subheading: 'Review and change the document title, author, subject and keywords before sharing the PDF.',
  },
  '/rotate-pdf': {
    path: '/rotate-pdf',
    title: 'Rotate PDF Pages — Change Orientation In-Browser',
    description: 'Rotate PDF pages permanently by 90, 180, or 270 degrees without server uploads.',
    heading: 'Rotate PDF',
    subheading: 'Reorient landscape and portrait pages directly in local memory.',
  },
  '/organize-pdf': {
    path: '/organize-pdf',
    title: 'Organize PDF Pages — Reorder, Rotate & Delete Pages Free',
    description: 'Visually organize, reorder, rotate, and delete pages from PDF documents locally in your browser. 100% private, zero server uploads.',
    heading: 'Organize PDF Pages',
    subheading: 'Drag and drop page thumbnails to reorder, rotate, or delete pages in memory.',
  },
  '/sanitize-pdf': {
    path: '/sanitize-pdf',
    title: 'Sanitize PDF — Remove Metadata, Forms & Hidden Data | 1into1',
    description: 'Deep-sanitize a PDF locally by rebuilding visible pages while removing metadata, XMP data, attachments, annotations, forms, scripts, links and hidden text layers.',
    heading: 'Sanitize PDF',
    subheading: 'Rebuild the visible document into a cleaner PDF without metadata, forms, scripts, attachments, annotations or hidden text layers.',
  },
  '/redact-pdf': {
    path: '/redact-pdf',
    title: 'Redact PDF Online — Permanently Black Out Text in Browser',
    description: 'Black out sensitive text, numbers, and images in PDF documents. 100% permanent client-side raster burn-in with zero server uploads.',
    heading: 'Redact PDF',
    subheading: 'Permanently burn blackout boxes into documents to destroy underlying text layers before sharing.',
  },
  '/crop-pdf': {
    path: '/crop-pdf',
    title: 'Crop PDF Margins Online Free — Clean Vector PDF Cropper',
    description: 'Crop PDF pages, remove margins, and trim whitespace without losing quality or rasterizing text. 100% private, client-side execution.',
    heading: 'Crop PDF',
    subheading: 'Trim margins and unwanted borders visually while keeping 100% crisp vector text.',
  },
  '/fill-pdf': {
    path: '/fill-pdf',
    title: 'PDF Forms Online Free — Fill and Flatten Privately | 1into1',
    description: 'Fill interactive PDF forms, check boxes, and flatten form fields directly in your browser. Zero server uploads and complete document privacy.',
    heading: 'PDF Forms',
    subheading: 'Populate interactive AcroForm fields and optionally bake inputs permanently into static text.',
  },
  '/grayscale-pdf': {
    path: '/grayscale-pdf',
    title: 'Convert PDF to Grayscale & Black and White Free Online',
    description: 'Convert PDF pages to grayscale or pure black-and-white photocopy style locally in your browser. Save printer toner and prepare court filings with zero uploads.',
    heading: 'B&W / Grayscale PDF',
    subheading: 'Turn color PDFs into monochrome or high-contrast black and white for ink-saving printing and archiving.',
  },
  '/resize-pdf': {
    path: '/resize-pdf',
    title: 'Resize PDF Pages to A4, Letter, Legal Free Online',
    description: 'Standardize PDF pages to A4, US Letter, Legal, or A3 dimensions in browser. Preserves 100% vector text quality with zero server uploads.',
    heading: 'Resize PDF',
    subheading: 'Convert mixed document formats to uniform A4, US Letter, or custom paper sizes.',
  },
  '/nup-pdf': {
    path: '/nup-pdf',
    title: 'Multiple Pages per Sheet PDF — 2, 4 or 9 Pages on One Sheet | 1into1',
    description: 'Print multiple PDF pages on one sheet. Convert documents to 2-on-1, 4-on-1, or 9-on-1 handouts locally in your browser. 100% vector clarity, zero uploads.',
    heading: 'Multiple Pages per Sheet',
    subheading: 'Combine 2, 4, or 9 pages onto a single sheet for pocket notes, study guides, and paper-saving printing.',
  },
  '/extract-images': {
    path: '/extract-images',
    title: 'Extract Images from PDF Online Free — Original Quality',
    description: 'Extract photos, figures, and embedded images from PDF documents without quality loss. Download as PNG or ZIP bundle in-browser with zero uploads.',
    heading: 'Extract Embedded Images from PDF',
    subheading: 'Extract embedded photos and graphics in their original dimensions and resolution.',
  },
  '/compare-pdf': {
    path: '/compare-pdf',
    title: 'Compare PDF Files Online — Side-by-Side & Overlay | 1into1',
    description: 'Visually compare two PDF versions page by page using side-by-side viewing or an adjustable overlay. Review contracts, reports and layout changes locally in your browser.',
    heading: 'Compare PDF',
    subheading: 'Review two PDF versions side by side or stack them with an adjustable overlay to inspect visual changes.',
  },
  '/repair-pdf': {
    path: '/repair-pdf',
    title: 'Repair PDF Online Free — Fix Corrupted and Unreadable PDFs',
    description: 'Fix damaged PDF cross-reference tables, stream errors, and corrupted trailers directly in your browser. 100% private client-side recovery.',
    heading: 'Repair & Rebuild Corrupted PDF',
    subheading: 'Reconstruct unreadable, broken, or damaged PDF documents with in-memory recovery.',
  },
  '/dark-mode-pdf': {
    path: '/dark-mode-pdf',
    title: 'Dark Mode PDF Converter Online Free — Invert PDF Colors',
    description: 'Convert bright white PDFs into OLED pure black, inverted negative, or warm sepia night-reading modes. 100% private in-browser processing.',
    heading: 'PDF Dark Mode & Invert Colors',
    subheading: 'Turn harsh white backgrounds into OLED pure black or warm sepia tones to eliminate eye strain.',
  },
  '/booklet-pdf': {
    path: '/booklet-pdf',
    title: 'Booklet PDF Online Free — Saddle Stitch Imposition | 1into1',
    description: 'Convert standard PDF pages into a print-ready folded booklet format. Automatic 4-page saddle-stitch imposition processed 100% locally in your browser.',
    heading: 'Booklet PDF',
    subheading: 'Rearrange pages into saddle-stitch print spreads to fold and staple into physical booklets.',
  },
  '/deskew-pdf': {
    path: '/deskew-pdf',
    title: 'Straighten PDF Online Free — Fix Tilted Scanned Documents | 1into1',
    description: 'Straighten tilted scanned PDF pages automatically or with precision grid angle adjustments. 100% private in-browser processing with zero server uploads.',
    heading: 'Straighten PDF',
    subheading: 'Correct crooked scans and align text baselines automatically or with fine manual rotation.',
  },
  '/ai-summary-pdf': {
    path: '/ai-summary-pdf',
    title: 'AI Summarizer — Bring Your Own AI Key | 1into1',
    description: 'Extract PDF text locally, then send an excerpt directly to the AI provider you choose after explicit consent. Bring your own key without a 1into1 AI proxy.',
    heading: 'AI Summarizer',
    subheading: 'Extract PDF text locally, then choose which AI provider receives the document excerpt after you approve cloud use.',
  },
  '/pdf-to-csv': {
    path: '/pdf-to-csv',
    title: 'PDF to Excel — Extract Tables Privately | 1into1',
    description: 'Extract text-based PDF tables into CSV or TSV locally in your browser. Adjust row and column detection, review the output, and use OCR first for scanned PDFs.',
    heading: 'PDF to Excel',
    subheading: 'Turn text-based PDF tables into CSV or TSV locally, with adjustable row and column detection.',
  },
  '/document-data-extractor': {
    path: '/document-data-extractor',
    title: 'Extract PDF Data to Excel & CSV — OCR & Private | 1into1',
    description: 'Extract structured rows and tables from digital or scanned PDFs, review and edit the detected data, then export to CSV or Excel locally in your browser.',
    heading: 'Extract PDF Data',
    subheading: 'Turn digital and scanned PDFs into editable spreadsheet data with page-aware OCR fallback and local processing.',
  },
  '/pdf-to-word': {
    path: '/pdf-to-word',
    title: 'PDF to Word Without Uploading — Private Editable DOCX | 1into1',
    description: 'Convert computer-created PDFs to editable Word DOCX files in your browser without uploading the PDF. Keep text, detected tables and artwork local and private.',
    heading: 'Convert PDF to Word Without Uploading',
    subheading: 'Create an editable Word document directly in your browser. Your PDF stays on your device, with no server upload or signup required.',
  },
  '/pdf-to-markdown': {
    path: '/pdf-to-markdown',
    title: 'PDF to Markdown Converter — Private, Local & AI-Ready | 1into1',
    description: 'Convert selectable PDF text into structured Markdown with heading and list detection. Copy or download the result locally for notes, documentation and AI workflows.',
    heading: 'Convert PDF to Markdown Privately',
    subheading: 'Extract selectable PDF text into structured Markdown locally for notes, documentation, ChatGPT and other LLM workflows.',
  },
  '/bank-statement-to-excel': {
    path: '/bank-statement-to-excel',
    title: 'Bank Statement PDF to Excel — Private Converter | 1into1',
    description: 'Convert bank statement PDFs into spreadsheet-ready data for Excel. Extract dates, debits, credits and balances locally in your browser, with CSV/TSV export and OCR support for scanned statements.',
    heading: 'Convert Bank Statement PDF to Excel',
    subheading: 'Extract statement transactions into spreadsheet-ready CSV or TSV locally, then open the result in Excel or another spreadsheet app.',
  },
  '/private-pii-secrets-auto-redactor': {
    path: '/private-pii-secrets-auto-redactor',
    title: 'Auto Redact PII & Secrets from PDF, TXT & CSV — Private | 1into1',
    description: 'Automatically scan PDF, TXT and CSV files for supported personal information, financial identifiers and exposed secrets. Review findings and create a redacted copy locally in your browser.',
    heading: 'Auto Redact PII & Secrets',
    subheading: 'Scan for supported personal data, financial identifiers and exposed credentials, then review and redact them locally.',
  },
  '/offline-pdf-redaction': {
    path: '/offline-pdf-redaction',
    title: 'Redact PDF Permanently — Burn Blackouts Locally | 1into1',
    description: 'Mark sensitive areas, burn permanent blackouts into the PDF output and run final verification before download. Redaction processing stays in your browser.',
    heading: 'Permanently Redact Sensitive PDF Content',
    subheading: 'Mark confidential areas, burn them into the page output and verify the finished redacted PDF before sharing.',
  },
  '/extract-pdf-for-llm': {
    path: '/extract-pdf-for-llm',
    title: 'PDF to Markdown for ChatGPT & Claude — Private | 1into1',
    description: 'Prepare selectable PDF text as Markdown for ChatGPT, Claude, Ollama and other LLMs. Extraction runs locally and does not automatically send the document to an AI provider.',
    heading: 'Prepare PDF Markdown for ChatGPT & Claude',
    subheading: 'Extract and review PDF text locally, then choose exactly what Markdown you want to use with an AI or LLM.',
  },
  '/compress-pdf-to-100kb': {
    path: '/compress-pdf-to-100kb',
    title: 'Compress PDF to 100KB Online — Free & Private | 1into1',
    description: 'Aim for a 100KB PDF target directly in your browser for forms, certificates and application portals. Process locally and inspect readability before uploading.',
    heading: 'Compress PDF to 100KB Online',
    subheading: 'Target 100KB for forms and application portals with local browser-based compression.',
  },
  '/compress-pdf-to-200kb': {
    path: '/compress-pdf-to-200kb',
    title: 'Compress PDF to 200KB Online — Free & Private | 1into1',
    description: 'Aim for a 200KB PDF target locally in your browser. Useful for certificates, applications and document portals where more clarity is possible than at smaller limits.',
    heading: 'Compress PDF to 200KB Online',
    subheading: 'Target 200KB while giving text, signatures and scanned images more room to remain readable.',
  },
  '/compress-pdf-to-500kb': {
    path: '/compress-pdf-to-500kb',
    title: 'Compress PDF to 500KB Online — Free & Private | 1into1',
    description: 'Aim for a 500KB PDF target directly in your browser for larger forms, scans and attachments. Local processing gives the document more room to preserve useful detail.',
    heading: 'Compress PDF to 500KB Online',
    subheading: 'Target 500KB for larger documents, scans and upload portals while preserving more useful detail.',
  },

  '/compress-pdf-to-300kb': {
    path: '/compress-pdf-to-300kb',
    title: 'Compress PDF to 300KB Online — Free & Private | 1into1',
    description: 'Aim for a 300KB PDF target directly in your browser for application portals, scanned documents and attachments. Process locally and review readability before upload.',
    heading: 'Compress PDF to 300KB Online',
    subheading: 'Target 300KB locally for portals and attachments while preserving more detail than stricter limits.',
  },
  '/compress-pdf-to-1mb': {
    path: '/compress-pdf-to-1mb',
    title: 'Compress PDF to 1MB Online — Free & Private | 1into1',
    description: 'Aim for a 1MB PDF target in your browser for email attachments and upload portals. Processing stays local; 1MB equals 1,024KB in this tool.',
    heading: 'Compress PDF to 1MB Online',
    subheading: 'Target 1MB (1,024KB) locally for attachments and portals with more room for readable detail.',
  },
  '/compress-pdf-to-2mb': {
    path: '/compress-pdf-to-2mb',
    title: 'Compress PDF to 2MB Online — Free & Private | 1into1',
    description: 'Aim for a 2MB PDF target in your browser for larger attachments, scans and upload limits. Processing stays local; 2MB equals 2,048KB in this tool.',
    heading: 'Compress PDF to 2MB Online',
    subheading: 'Target 2MB (2,048KB) locally when the destination allows more room for page quality.',
  },
  "/privacy": {"path": "/privacy", "title": "Privacy policy | 1into1 PDF", "description": "How your documents, optional cloud AI and local browser storage are handled.", "heading": "Privacy policy", "subheading": "How your documents, optional cloud AI and local browser storage are handled."},
  "/terms": {"path": "/terms", "title": "Terms of service | 1into1 PDF", "description": "Understand permitted use, device limits and purchase terms.", "heading": "Terms of service", "subheading": "Understand permitted use, device limits and purchase terms."},
  "/bates-numbering": {"path": "/bates-numbering", "title": "Bates Numbering PDF Online — Private Legal Stamping | 1into1", "description": "Add sequential Bates numbers to PDF pages for legal discovery and document review. Set prefix, suffix, start number, digit padding and position locally in your browser.", "heading": "Bates Numbering", "subheading": "Stamp sequential legal reference numbers with your own prefix, suffix, starting number, padding and position."},
  "/text-to-pdf": {"path": "/text-to-pdf", "title": "Text to PDF | 1into1 PDF", "description": "Write, format and turn your text into a PDF in your browser.", "heading": "Text to PDF", "subheading": "Write, format and turn your text into a PDF in your browser."},
  "/ocr-pdf": {"path": "/ocr-pdf", "title": "OCR PDF Online — Make Scanned PDFs Searchable Privately | 1into1", "description": "Run OCR on scanned PDFs in your browser and add an invisible searchable, selectable text layer. English OCR runs locally after required resources are available.", "heading": "OCR PDF", "subheading": "Add an invisible text layer so scanned pages become searchable and selectable while the visible PDF stays unchanged."},
  "/csv-to-pdf": {"path": "/csv-to-pdf", "title": "CSV to PDF | 1into1 PDF", "description": "Turn spreadsheet data into a clear, shareable PDF table.", "heading": "CSV to PDF", "subheading": "Turn spreadsheet data into a clear, shareable PDF table."},
  "/visual-editor": {"path": "/visual-editor", "title": "Add Text & Shapes to PDF | 1into1", "description": "Add text, images and shapes to a PDF without uploading it.", "heading": "Add text & shapes", "subheading": "Add text, images and shapes to a PDF without uploading it."},
  "/code-to-pdf": {"path": "/code-to-pdf", "title": "Code to PDF | 1into1 PDF", "description": "Create a readable PDF of your code with syntax highlighting.", "heading": "Code to PDF", "subheading": "Create a readable PDF of your code with syntax highlighting."},
  "/html-to-pdf": {"path": "/html-to-pdf", "title": "HTML to PDF | 1into1 PDF", "description": "Convert HTML or a receipt into a PDF, right in your browser.", "heading": "HTML to PDF", "subheading": "Convert HTML or a receipt into a PDF, right in your browser."},
};
