export interface ToolMeta {
  path: string;
  title: string;
  description: string;
  heading: string;
  subheading: string;
}

export const TOOLS_METADATA: Record<string, ToolMeta> = {
  '/': {
    path: '/',
    title: '1into1 PDF — Free, Private PDF & Image Tools (Zero Uploads)',
    description: 'Compress, merge, split, OCR, and convert PDFs and HEIC images 100% locally in your browser. Disconnect your internet and test—files never leave your device.',
    heading: 'Free PDF Tools That Never Upload Your Files',
    subheading: 'Local-first processing powered by your browser memory. Turn off your Wi-Fi and everything still works.',
  },
  '/compress-pdf': {
    path: '/compress-pdf',
    title: 'Compress PDF Offline — Reduce File Size Privately',
    description: 'Compress PDF documents client-side without uploading to any server. Fast, lossless, and secure.',
    heading: 'Compress PDF Locally',
    subheading: 'Reduce PDF file size securely in your browser with zero data transmission.',
  },
  '/merge-pdf': {
    path: '/merge-pdf',
    title: 'Merge PDF Online & Offline — Combine PDF Files Privately',
    description: 'Merge multiple PDF files into one single document client-side with zero data uploads.',
    heading: 'Merge Multiple PDFs',
    subheading: 'Combine and organize your documents without sending files to remote servers.',
  },
  '/split-pdf': {
    path: '/split-pdf',
    title: 'Split PDF Pages Privately — Zero Server Uploads',
    description: 'Extract pages or split PDF documents into multiple files completely offline.',
    heading: 'Split PDF Documents',
    subheading: 'Separate individual pages or ranges locally on your device.',
  },
  '/image-to-pdf': {
    path: '/image-to-pdf',
    title: 'Convert Images to PDF — JPG, PNG to PDF Locally',
    description: 'Convert JPG, PNG, and WebP images to high-quality PDF files directly in your browser.',
    heading: 'Image to PDF Converter',
    subheading: 'Bundle images into a clean PDF document without cloud processing.',
  },
  '/pdf-to-jpg': {
    path: '/pdf-to-jpg',
    title: 'Convert PDF to JPG Images — High Resolution & Private',
    description: 'Render and extract high-resolution JPG images from any PDF file locally.',
    heading: 'PDF to High-Res JPG',
    subheading: 'Export each PDF page as an image directly in your browser session.',
  },
  '/heic-to-jpg': {
    path: '/heic-to-jpg',
    title: 'HEIC to JPG Converter Online & Private (EXIF Stripped) | 1into1',
    description: 'Convert iPhone HEIC/HEIF photos to JPG locally in your browser. Automatically strip GPS location and private camera EXIF data with zero server uploads.',
    heading: 'Convert HEIC to JPG & Strip EXIF',
    subheading: 'Convert Apple photos to standard JPG and remove sensitive GPS metadata locally.',
  },
  '/remove-pages': {
    path: '/remove-pages',
    title: 'Delete PDF Pages — Clean & Remove Unwanted Pages',
    description: 'Remove unwanted pages from your PDF file without uploading confidential data.',
    heading: 'Remove PDF Pages',
    subheading: 'Select and permanently delete pages from your document in memory.',
  },
  '/watermark-pdf': {
    path: '/watermark-pdf',
    title: 'Add Watermark to PDF — In-Browser PDF Protection',
    description: 'Add custom text watermarks to all PDF pages securely without server uploads.',
    heading: 'Stamp PDF Watermark',
    subheading: 'Protect confidential files by adding custom stamps locally.',
  },
  '/page-numbers': {
    path: '/page-numbers',
    title: 'Add Page Numbers to PDF — Flexible Formatting Locally',
    description: 'Number PDF pages with customizable positioning and styles completely offline.',
    heading: 'Insert Page Numbers',
    subheading: 'Add sequential pagination across your PDF without tracking.',
  },
  '/extract-text': {
    path: '/extract-text',
    title: 'Extract Text from PDF — Private In-Browser Text Reader',
    description: 'Extract raw text from PDF files directly inside the browser using WebAssembly.',
    heading: 'Extract PDF Text',
    subheading: 'Copy raw text content from your documents with zero network requests.',
  },
  '/sign-pdf': {
    path: '/sign-pdf',
    title: 'Sign PDF Document Privately — Draw & Place Signatures',
    description: 'Electronically sign contracts and forms directly in your browser without cloud uploads.',
    heading: 'Sign PDF Online & Offline',
    subheading: 'Draw and place your electronic signature securely on any PDF page.',
  },
  '/protect-pdf': {
    path: '/protect-pdf',
    title: 'Password Protect PDF — 128-bit Client-Side Encryption',
    description: 'Encrypt your PDF files with standard password protection without sending files over the web.',
    heading: 'Password Protect PDF',
    subheading: 'Apply 128-bit encryption directly inside your browser.',
  },
  '/unlock-pdf': {
    path: '/unlock-pdf',
    title: 'Unlock Protected PDF — Remove PDF Password Locally',
    description: 'Decrypt and remove password restrictions from your PDF files without server logs.',
    heading: 'Unlock PDF Document',
    subheading: 'Decrypt and save an unrestricted copy entirely on your machine.',
  },
  '/edit-metadata': {
    path: '/edit-metadata',
    title: 'Edit PDF Metadata — Clean Title, Author, Keywords Privately',
    description: 'Inspect and edit title, author, subject, and producer metadata of any PDF locally.',
    heading: 'Edit Document Metadata',
    subheading: 'View or scrub embedded metadata tags cleanly in your browser.',
  },
  '/rotate-pdf': {
    path: '/rotate-pdf',
    title: 'Rotate PDF Pages — Change Orientation In-Browser',
    description: 'Rotate PDF pages permanently by 90, 180, or 270 degrees without server uploads.',
    heading: 'Rotate PDF Pages',
    subheading: 'Reorient landscape and portrait pages directly in local memory.',
  },
  '/organize-pdf': {
    path: '/organize-pdf',
    title: 'Organize PDF Pages — Reorder, Rotate & Delete Pages Free',
    description: 'Visually organize, reorder, rotate, and delete pages from PDF documents locally in your browser. 100% private, zero server uploads.',
    heading: 'Organize PDF Pages',
    subheading: 'Drag and drop page thumbnails to reorder, rotate, or delete pages in memory.',
  },
  '/sanitize-pdf': {
    path: '/sanitize-pdf',
    title: 'Sanitize PDF — Strip Hidden Metadata & Tracking Tags',
    description: 'Remove author, creation dates, software fingerprints, and XMP metadata from PDF files in your browser. 100% private and offline.',
    heading: 'Sanitize PDF Metadata',
    subheading: 'Wipe hidden tracking identifiers, hardware signatures, and author data before sharing.',
  },
  '/redact-pdf': {
    path: '/redact-pdf',
    title: 'Redact PDF Online — Permanently Black Out Text in Browser',
    description: 'Black out sensitive text, numbers, and images in PDF documents. 100% permanent client-side raster burn-in with zero server uploads.',
    heading: 'True PDF Redaction',
    subheading: 'Permanently burn blackout boxes into documents to destroy underlying text layers before sharing.',
  },
  '/crop-pdf': {
    path: '/crop-pdf',
    title: 'Crop PDF Margins Online Free — Clean Vector PDF Cropper',
    description: 'Crop PDF pages, remove margins, and trim whitespace without losing quality or rasterizing text. 100% private, client-side execution.',
    heading: 'Crop PDF Margins',
    subheading: 'Trim margins and unwanted borders visually while keeping 100% crisp vector text.',
  },
  '/fill-pdf': {
    path: '/fill-pdf',
    title: 'Fill & Flatten PDF Forms Online Free — 100% In-Browser',
    description: 'Fill interactive PDF forms, check boxes, and flatten form fields directly in your browser. Zero server uploads and complete document privacy.',
    heading: 'Fill & Flatten PDF Forms',
    subheading: 'Populate interactive AcroForm fields and optionally bake inputs permanently into static text.',
  },
  '/grayscale-pdf': {
    path: '/grayscale-pdf',
    title: 'Convert PDF to Grayscale & Black and White Free Online',
    description: 'Convert PDF pages to grayscale or pure black-and-white photocopy style locally in your browser. Save printer toner and prepare court filings with zero uploads.',
    heading: 'Convert PDF to Grayscale & B&W',
    subheading: 'Turn color PDFs into monochrome or high-contrast black and white for ink-saving printing and archiving.',
  },
  '/resize-pdf': {
    path: '/resize-pdf',
    title: 'Resize PDF Pages to A4, Letter, Legal Free Online',
    description: 'Standardize PDF pages to A4, US Letter, Legal, or A3 dimensions in browser. Preserves 100% vector text quality with zero server uploads.',
    heading: 'Resize & Standardize PDF Pages',
    subheading: 'Convert mixed document formats to uniform A4, US Letter, or custom paper sizes.',
  },
  '/nup-pdf': {
    path: '/nup-pdf',
    title: 'Multiple Pages per Sheet (N-Up) PDF Converter Free Online',
    description: 'Print multiple PDF pages on one sheet. Convert documents to 2-on-1, 4-on-1, or 9-on-1 handouts locally in your browser. 100% vector clarity, zero uploads.',
    heading: 'Multiple Pages Per Sheet (N-Up)',
    subheading: 'Combine 2, 4, or 9 pages onto a single sheet for pocket notes, study guides, and paper-saving printing.',
  },
  '/extract-images': {
    path: '/extract-images',
    title: 'Extract Images from PDF Online Free — Original Quality',
    description: 'Extract photos, figures, and embedded images from PDF documents without quality loss. Download as PNG or ZIP bundle in-browser with zero uploads.',
    heading: 'Extract Embedded Images from PDF',
    subheading: 'Extract embedded photos and graphics in their original dimensions and resolution.',
  },
  '/compare-pdf': {
    path: '/compare-pdf',
    title: 'Compare PDF Files Online Free — Visual Diff & Revision Checker',
    description: 'Compare two PDF documents side-by-side or via visual overlay diff. Detect text alterations, contract revisions, and drawing changes 100% privately in-browser.',
    heading: 'Visual PDF Compare & Diff',
    subheading: 'Inspect differences and detect contract revisions side-by-side or with visual pixel subtraction in memory.',
  },
  '/repair-pdf': {
    path: '/repair-pdf',
    title: 'Repair PDF Online Free — Fix Corrupted and Unreadable PDFs',
    description: 'Fix damaged PDF cross-reference tables, stream errors, and corrupted trailers directly in your browser. 100% private client-side recovery.',
    heading: 'Repair & Rebuild Corrupted PDF',
    subheading: 'Reconstruct unreadable, broken, or damaged PDF documents with in-memory recovery.',
  },
  '/dark-mode-pdf': {
    path: '/dark-mode-pdf',
    title: 'Dark Mode PDF Converter Online Free — Invert PDF Colors',
    description: 'Convert bright white PDFs into OLED pure black, inverted negative, or warm sepia night-reading modes. 100% private in-browser processing.',
    heading: 'PDF Dark Mode & Invert Colors',
    subheading: 'Turn harsh white backgrounds into OLED pure black or warm sepia tones to eliminate eye strain.',
  },
  '/booklet-pdf': {
    path: '/booklet-pdf',
    title: 'PDF Booklet Maker Online Free — Saddle Stitch Imposition',
    description: 'Convert standard PDF pages into a print-ready folded booklet format. Automatic 4-page saddle-stitch imposition processed 100% locally in your browser.',
    heading: 'PDF Booklet Maker',
    subheading: 'Rearrange pages into saddle-stitch print spreads to fold and staple into physical booklets.',
  },
  '/deskew-pdf': {
    path: '/deskew-pdf',
    title: 'Deskew PDF Online Free — Auto-Straighten Scanned Documents',
    description: 'Straighten tilted scanned PDF pages automatically or with precision grid angle adjustments. 100% private in-browser processing with zero server uploads.',
    heading: 'Deskew & Straighten Scanned PDF',
    subheading: 'Correct crooked scans and align text baselines automatically or with fine manual rotation.',
  },
  '/ai-summary-pdf': {
    path: '/ai-summary-pdf',
    title: 'Privacy-Native AI PDF Summary & Chat Free — Zero Server Egress',
    description: 'Summarize documents and chat with PDFs directly in your browser. Bring Your Own Key with zero intermediate server uploads.',
    heading: 'Privacy-Native AI PDF Chat',
    subheading: 'Summarize, interrogate, and extract key action items from documents with zero server data storage.',
  },
  '/pdf-to-csv': {
    path: '/pdf-to-csv',
    title: 'PDF to CSV Converter Online Free — Bank Statement Table Extractor',
    description: 'Convert PDF tables, bank statements, and invoices into clean CSV and Excel files. 100% private in-browser coordinate parsing with zero server uploads.',
    heading: 'PDF to CSV Table Extractor',
    subheading: 'Extract tabular statements and invoices directly into CSV format without financial data leaving your computer.',
  },
  '/pdf-to-markdown': {
    path: '/pdf-to-markdown',
    title: 'PDF to Markdown Converter Online Free — Clean LLM Ingestion',
    description: 'Convert PDF files into formatted Markdown with headings, bullet lists, and token estimation. 100% private in-browser extraction with zero server uploads.',
    heading: 'PDF to Markdown Converter',
    subheading: 'Turn research papers, manuals, and documents into clean Markdown for prompt engineering and local LLM ingestion.',
  },
  '/bank-statement-to-excel': {
    path: '/bank-statement-to-excel',
    title: 'Offline Bank Statement to Excel Converter — 100% Private',
    description: 'Convert bank statements and transaction tables into Excel and CSV without financial data ever touching an external server.',
    heading: 'Bank Statement to Excel Table Extractor',
    subheading: 'Extract tabular statements locally in browser memory. No financial telemetry leaves your machine.',
  },
  '/offline-pdf-redaction': {
    path: '/offline-pdf-redaction',
    title: 'Offline PDF Redaction Tool — Permanent Blackout Censor',
    description: 'Permanently redact sensitive PII, SSNs, and trade secrets from PDFs directly in browser RAM with zero server processing.',
    heading: 'Client-Side PDF Redaction & Sanitization',
    subheading: 'True pixel rasterization sanitization ensuring sensitive terms cannot be uncovered or reversed.',
  },
  '/extract-pdf-for-llm': {
    path: '/extract-pdf-for-llm',
    title: 'Extract PDF for Local LLMs & NotebookLM — Zero Uploads',
    description: 'Extract clean, structured Markdown from research papers and confidential briefs to feed local Ollama or Claude instances.',
    heading: 'PDF to Markdown for LLM Ingestion',
    subheading: 'Reconstruct structured headings and lists locally without leaking internal documentation.',
  },
  '/compress-pdf-to-100kb': {
    path: '/compress-pdf-to-100kb',
    title: 'Compress PDF to 100KB Online — 100% Free & Private',
    description: 'Compress your PDF to under 100KB offline in browser memory. Ideal for government portals, job applications, and exam uploads.',
    heading: 'Compress PDF Under 100KB',
    subheading: 'Precision client-side compression targeting strictly under 100KB with zero server uploads.',
  },
  '/compress-pdf-to-200kb': {
    path: '/compress-pdf-to-200kb',
    title: 'Compress PDF to 200KB Online — Strict Target Size',
    description: 'Reduce PDF file size to under 200KB directly in your browser. Fast, free, and completely offline.',
    heading: 'Compress PDF Under 200KB',
    subheading: 'Reduce PDF size to under 200KB with lossless structural tuning and dynamic raster scaling.',
  },
  '/compress-pdf-to-500kb': {
    path: '/compress-pdf-to-500kb',
    title: 'Compress PDF to 500KB Online — Free Offline Compression',
    description: 'Fit large PDFs under 500KB without uploading sensitive documents to external servers.',
    heading: 'Compress PDF Under 500KB',
    subheading: 'Hit exact 500KB file thresholds reliably while preserving readable text.',
  },
};