// Concrete capabilities, not unverified claims of competitor exclusivity.
export const TOOL_COPY: Record<string, string> = {
  '/compress-pdf': 'Choose your target KB. Precision compression, with no PDF upload.',
  '/merge-pdf': 'Bring separate PDFs together in your chosen order, on your device.',
  '/split-pdf': 'Pick exact page ranges. Save one PDF or download separate files in a ZIP.',
  '/organize-pdf': 'Reorder, rotate and remove pages in one visual workspace.',
  '/crop-pdf': 'Set your crop once. Apply it to one page or your entire PDF.',
  '/rotate-pdf': 'Straighten sideways pages without uploading your document.',
  '/remove-pages': 'Keep what matters. Remove selected pages from your PDF.',
  '/resize-pdf': 'Fit your PDF to a new paper size with control over content placement.',
  '/nup-pdf': 'Put multiple PDF pages on one sheet, ready for compact printing.',
  '/booklet-pdf': 'Arrange your PDF into booklet spreads for folding and printing.',
  '/deskew-pdf': 'Straighten tilted scanned pages locally, before sharing or printing.',
  '/sanitize-pdf': 'Clear author, title and selected hidden metadata before sharing.',
  '/redact-pdf': 'Burn selected redactions into rendered pages, rather than overlaying text.',
  '/protect-pdf': 'Add a password locally. Your document stays off upload servers.',
  '/unlock-pdf': 'Use your PDF password to create a copy that opens without it.',
  '/sign-pdf': 'Draw your signature and place it precisely on the page, using touch.',
  '/watermark-pdf': 'Stamp text or your own image onto pages with adjustable placement.',
  '/bates-numbering': 'Add sequential reference numbers with your own prefix and padding.',
  '/compare-pdf': 'Compare two PDFs visually and inspect changes page by page.',
  '/repair-pdf': 'Try rebuilding a damaged PDF locally, without sharing the original.',
  '/text-to-pdf': 'Write, format and preview real PDF pages, with a saved browser draft.',
  '/ai-summary-pdf': 'Bring your own AI provider. Choose where your document excerpt goes.',
  '/ocr-pdf': 'Turn scans into searchable PDFs with OCR running on your device.',
  '/fill-pdf': 'Fill supported PDF fields, then flatten the finished form for sharing.',
  '/extract-images': 'Pull embedded images out of a PDF and collect them in a ZIP.',
  '/dark-mode-pdf': 'Create a darker PDF for reading, with page-by-page filter previews.',
  '/grayscale-pdf': 'Create a black-and-white PDF for a cleaner print or shared copy.',
  '/image-to-pdf': 'Arrange your photos in order and turn them into one PDF.',
  '/pdf-to-jpg': 'Turn PDF pages into JPG images and download them together.',
  '/heic-to-jpg': 'Convert supported iPhone HEIC photos into easy-to-share JPG files.',
  '/pdf-to-text': 'Extract selectable PDF text locally, ready to copy or download.',
  '/edit-metadata': 'Inspect and change your PDF’s title, author and document details.',
  '/page-numbers': 'Choose your starting number and place page numbers where you need them.',
  '/pdf-to-csv': 'Extract text-based tables to CSV with adjustable row and column detection.',
  '/pdf-to-markdown': 'Turn PDF text into Markdown for notes, documentation and AI workflows.',
  '/csv-to-pdf': 'Turn rows of CSV data into a paginated PDF table.',
  '/edit-pdf': 'Edit supported existing text with its original font. Local processing, with a before-and-after preview.',
  '/add-text-to-pdf': 'Place new text, images and shapes on your PDF with a live page preview.',
  '/code-to-pdf': 'Share code as a paginated PDF with readable syntax highlighting.',
  '/html-to-pdf': 'Turn HTML into A4, Letter or a continuous receipt-sized PDF.',
};
