// Concrete capabilities, not unverified claims of competitor exclusivity.
export const TOOL_COPY: Record<string, string> = {
  '/compress-pdf': 'Choose your target KB. Precision compression, with no PDF upload.',
  '/compress-pdf-to-50kb': 'Aim for a 50KB PDF target for strict upload limits, then reopen the result and check small text, signatures and stamps.',
  '/compress-pdf-to-100kb': 'Aim for a 100KB PDF target for forms and application portals, with compression running locally in your browser.',
  '/compress-pdf-to-200kb': 'Aim for a 200KB PDF target while giving document text and scanned details more room than smaller limits.',
  '/compress-pdf-to-300kb': 'Aim for a 300KB PDF target for application portals and attachments while keeping processing local in your browser.',
  '/compress-pdf-to-500kb': 'Aim for a 500KB PDF target for larger scans, attachments and portals while preserving more useful page detail.',
  '/compress-pdf-to-1mb': 'Aim for a 1MB (1,024KB) PDF target for email attachments and upload portals, processed locally in your browser.',
  '/compress-pdf-to-2mb': 'Aim for a 2MB (2,048KB) PDF target when the destination allows more room for page quality, processed locally in your browser.',
  '/merge-pdf': 'Bring separate PDFs together in your chosen order, on your device.',
  '/split-pdf': 'Pick exact page ranges. Save one PDF or download separate files in a ZIP.',
  '/organize-pdf': 'Reorder, rotate and remove pages in one visual workspace.',
  '/crop-pdf': 'Set your crop once. Apply it to one page or your entire PDF.',
  '/rotate-pdf': 'Straighten sideways pages without uploading your document.',
  '/remove-pages': 'Keep what matters. Remove selected pages from your PDF.',
  '/resize-pdf': 'Fit your PDF to a new paper size with control over content placement.',
  '/nup-pdf': 'Put multiple PDF pages on one sheet, ready for compact printing.',
  '/booklet-pdf': 'Arrange your PDF into booklet spreads for folding and printing.',
  '/deskew-pdf': 'Straighten tilted scanned pages locally, before sharing or printing.',
  '/sanitize-pdf': 'Rebuild visible PDF pages while removing metadata, forms, annotations, attachments, scripts, links and hidden text layers.',
  '/private-pii-secrets-auto-redactor': 'Scan PDF, TXT and CSV files for supported PII and exposed secrets, review each finding, then create a redacted copy locally.',
  '/redact-pdf': 'Burn selected redactions into rendered pages, rather than overlaying text.',
  '/offline-pdf-redaction': 'Mark confidential areas, burn permanent blackouts into the PDF output and verify the finished file before download.',
  '/protect-pdf': 'Add standard 128-bit password protection locally and download the encrypted PDF copy.',
  '/unlock-pdf': 'Use your PDF password to create a copy that opens without it.',
  '/sign-pdf': 'Draw your signature and place it precisely on the page, using touch.',
  '/watermark-pdf': 'Stamp text or your own image onto pages with adjustable placement.',
  '/bates-numbering': 'Add sequential reference numbers with your own prefix and padding.',
  '/compare-pdf': 'Compare two PDFs page by page using side-by-side viewing or an adjustable visual overlay.',
  '/repair-pdf': 'Try rebuilding a damaged PDF locally, without sharing the original.',
  '/text-to-pdf': 'Write, format and preview real PDF pages, with a saved browser draft.',
  '/ai-summary-pdf': 'Bring your own AI provider. Choose where your document excerpt goes.',
  '/ocr-pdf': 'Run English OCR locally and add an invisible text layer so scanned PDF pages become searchable, selectable and copyable.',
  '/fill-pdf': 'Fill supported PDF fields, then flatten the finished form for sharing.',
  '/extract-images': 'Pull embedded images out of a PDF and collect them in a ZIP.',
  '/dark-mode-pdf': 'Create a darker PDF for reading, with page-by-page filter previews.',
  '/grayscale-pdf': 'Create a black-and-white PDF for a cleaner print or shared copy.',
  '/image-to-pdf': 'Arrange your photos in order and turn them into one PDF.',
  '/pdf-to-jpg': 'Turn PDF pages into JPG images and download them together.',
  '/heic-to-jpg': 'Convert supported iPhone HEIC photos into easy-to-share JPG files.',
  '/pdf-to-text': 'Extract selectable PDF text locally, ready to copy or download.',
  '/edit-metadata': 'Inspect and change the PDF title, author, subject and keywords locally before saving a new copy.',
  '/page-numbers': 'Choose your starting number and place page numbers where you need them.',
  '/pdf-to-csv': 'Extract text-based tables to CSV with adjustable row and column detection.',
  '/bank-statement-to-excel': 'Extract text-based bank-statement transactions into CSV or TSV that you can open and review in Excel or another spreadsheet app.',
  '/document-data-extractor': 'Extract structured rows from digital or scanned PDFs, review and edit the result, then export to CSV or Excel.',
  '/pdf-to-word': 'Convert digital PDFs to editable Word DOCX files without uploading them. Processing stays private on your device.',
  '/pdf-to-markdown': 'Turn selectable PDF text into Markdown with heading and list detection, then copy or download the result locally.',
  '/extract-pdf-for-llm': 'Prepare selectable PDF text as Markdown locally, review it, then choose what you share with ChatGPT, Claude or another LLM.',
  '/csv-to-pdf': 'Turn rows of CSV data into a paginated PDF table.',
  '/edit-pdf': 'Edit supported existing text with its original font. Local processing, with a before-and-after preview.',
  '/code-to-pdf': 'Share code as a paginated PDF with readable syntax highlighting.',
  '/html-to-pdf': 'Turn HTML into A4, Letter or a continuous receipt-sized PDF.',
};
